### ISSUE TITLE
adopt into actix-extras

### ISSUE THREAD

**Issue by robjtede** [errmac-v/actix-limitation#8]
Hey, this library is recommended on our actix-extras repo readme but seems dormant. If you are willing, I'd be happy to adopt ownership of this crate into the actix organisation.

**Comment by 0xmad** [comment]
@robjtede sure, not a problem. This crate was my pet project to dive into the rust and actix and this is a surprise for me that it's recommended on actix-extras :)

**Comment by robjtede** [comment]
Great. It's been on my mind to create a first party rate limiting library so being able to adopt an existing name is a bonus. If you can assign me the publish permissions on crates.io I can handle the rest.

**Comment by 0xmad** [comment]
Just sent an invitation.
